# Generated by Django 3.2.19 on 2023-06-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMate_userDetails',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
                ('profilePic', models.ImageField(default='/images/user.png', upload_to='media/')),
                ('bio', models.CharField(default='Hey there! I am using TaskMate.', max_length=500)),
            ],
        ),
    ]
