# Generated by Django 3.2.19 on 2023-06-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMate_taskDetails',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('deadlineDate', models.CharField(max_length=50)),
                ('deadlineTime', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=300)),
            ],
        ),
    ]
